# Generated by Django 6.0.2 on 2026-03-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmortem',
            name='restock',
        ),
    ]
