# Generated by Django 6.0.2 on 2026-03-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_postmortem_restock'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmortem',
            name='slack_first_reply_ts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postmortem',
            name='slack_thread_ts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
